package com.aquinnmo.timber.liveupdate

import android.app.Notification
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.os.Build
import android.util.Log
import expo.modules.kotlin.modules.Module
import expo.modules.kotlin.modules.ModuleDefinition
import expo.modules.kotlin.records.Field
import expo.modules.kotlin.records.Record

private const val TAG = "LiveUpdateNotification"
private const val CHANNEL_ID = "active-workout" // created by Notifee, see utils/workout-notification.android.ts
private const val NOTIFICATION_ID = 4242
private const val COLOR_STARTED = 0xFFE54242.toInt() // app/(tabs)/_layout.tsx:9
private const val COLOR_PENDING = 0xFF555555.toInt() // app/(tabs)/_layout.tsx:10

// Notification.EXTRA_REQUEST_PROMOTED_ONGOING is only in the android-36.1 SDK; this
// project compiles against 36 (ExpoModulesCorePlugin.gradle:65). The key string is
// stable across both, so use it directly rather than bumping compileSdk.
private const val EXTRA_REQUEST_PROMOTED_ONGOING = "android.requestPromotedOngoing"

class LiveUpdateSegment : Record {
  @Field val sets: Int = 0
  @Field val started: Boolean = false
}

class LiveUpdateNotificationPayload : Record {
  @Field val title: String = ""
  @Field val text: String = ""
  @Field val startedAtMillis: Long = 0
  @Field val shortCriticalText: String = ""
  @Field val progress: Int = 0
  @Field val segments: List<LiveUpdateSegment> = emptyList()
}

class LiveUpdateNotificationModule : Module() {
  override fun definition() = ModuleDefinition {
    Name("LiveUpdateNotification")

    Function("isSupported") {
      isSupported()
    }

    Function("show") { payload: LiveUpdateNotificationPayload ->
      show(payload)
    }

    Function("dismiss") {
      dismiss()
    }
  }

  private val notificationManager: NotificationManager?
    get() {
      val context = appContext.reactContext ?: return null
      return context.getSystemService(Context.NOTIFICATION_SERVICE) as? NotificationManager
    }

  private fun isSupported(): Boolean {
    if (Build.VERSION.SDK_INT < 36) return false
    return notificationManager?.canPostPromotedNotifications() ?: false
  }

  private fun show(payload: LiveUpdateNotificationPayload): Boolean {
    if (Build.VERSION.SDK_INT < 36) return false
    val context = appContext.reactContext ?: return false
    val manager = notificationManager ?: return false

    return try {
      val progressStyle = Notification.ProgressStyle()
        .setProgressSegments(
          payload.segments.map { segment ->
            Notification.ProgressStyle.Segment(segment.sets)
              .setColor(if (segment.started) COLOR_STARTED else COLOR_PENDING)
          }
        )
        .setProgress(payload.progress)
        .setStyledByProgress(false) // keep each segment's own color instead of recoloring by tracker position

      // ic_stat_timber is generated by csx.2; fall back to the launcher icon until it lands.
      val smallIconRes = context.resources
        .getIdentifier("ic_stat_timber", "drawable", context.packageName)
        .takeIf { it != 0 }
        ?: context.applicationInfo.icon

      val contentIntent = context.packageManager.getLaunchIntentForPackage(context.packageName)?.let {
        PendingIntent.getActivity(context, 0, it, PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE)
      }

      val builder = Notification.Builder(context, CHANNEL_ID)
        .setStyle(progressStyle)
        .setOngoing(true)
        .setCategory(Notification.CATEGORY_PROGRESS)
        .setWhen(payload.startedAtMillis)
        .setUsesChronometer(true)
        .setShortCriticalText(payload.shortCriticalText)
        .setSmallIcon(smallIconRes)
        .setContentTitle(payload.title)
        .setContentText(payload.text)
      contentIntent?.let { builder.setContentIntent(it) }
      builder.extras.putBoolean(EXTRA_REQUEST_PROMOTED_ONGOING, true)

      val notification = builder.build()
      manager.notify(NOTIFICATION_ID, notification)
      notification.hasPromotableCharacteristics()
    } catch (e: Exception) {
      Log.w(TAG, "show() failed, JS should fall back to Notifee", e)
      false
    }
  }

  private fun dismiss() {
    notificationManager?.cancel(NOTIFICATION_ID)
  }
}
